[package]
name = "piggy-box"
version = "0.1.0"
edition = "2021"

[dependencies]
piggy-piv = { path = "../piggy-piv" }
openssl = "0.10"
ssh-key = { version = "0.6", features = ["alloc", "ecdsa"] }
hex = "0.4"
base64 = "0.22"
thiserror = "2"
tracing = "0.1"
zeroize = { version = "1", features = ["derive"] }
sharks = "0.5"

[dev-dependencies]
openssl = "0.10"
