// Code generated by dagnabit (0.3.3+8d3cce0); DO NOT EDIT.

package markl

import internal "github.com/amarbel-llc/piggy/go/markl/internal/bravo/markl"

type FormatPub = internal.FormatPub
type FormatSec = internal.FormatSec
type FuncFormatPubVerify = internal.FuncFormatPubVerify

// TODO switch to accepting bytes?
type FuncFormatSecGenerate = internal.FuncFormatSecGenerate
type FuncFormatSecGetIOWrapper = internal.FuncFormatSecGetIOWrapper
type FuncFormatSecGetPublicKey = internal.FuncFormatSecGetPublicKey
type FuncFormatSecSign = internal.FuncFormatSecSign
type Purpose = internal.Purpose
type PurposeType = internal.PurposeType

// RegisterPurposeOpts is the public registration shape for purposes.
//
// Related is a free-form role → purposeId map (see ADR 0006). Values are
// validated lazily: lookups via Purpose.GetRelated succeed for any registered
// role, and a downstream caller passing the result to GetPurpose is what
// surfaces typos.
type RegisterPurposeOpts = internal.RegisterPurposeOpts

var GetDigestTypeForSigType = internal.GetDigestTypeForSigType
var GetMotherSigTypeForSigType = internal.GetMotherSigTypeForSigType
var GetPurpose = internal.GetPurpose
var NonceGenerate = internal.NonceGenerate
var NonceGenerate32 = internal.NonceGenerate32

// RegisterPurpose installs a Purpose in the package-global registry. Panics
// if Id is already registered, or if FormatIds contains a duplicate. Returns
// the constructed Purpose so callers may keep a typed handle.
var RegisterPurpose = internal.RegisterPurpose

// Blob Digests
const PurposeBlobDigestV1 = internal.PurposeBlobDigestV1

// Blob-Store-Config Digests
const PurposeBlobStoreConfigDigestV1 = internal.PurposeBlobStoreConfigDigestV1
const PurposeMadderPrivateKeyV0 = internal.PurposeMadderPrivateKeyV0
const PurposeMadderPrivateKeyV1 = internal.PurposeMadderPrivateKeyV1
const PurposeMadderPubKeyV1 = internal.PurposeMadderPubKeyV1

// Object Digests
const PurposeObjectDigestV1 = internal.PurposeObjectDigestV1
const PurposeObjectDigestV2 = internal.PurposeObjectDigestV2

// Object Mother Sigs
const PurposeObjectMotherSigV1 = internal.PurposeObjectMotherSigV1
const PurposeObjectMotherSigV2 = internal.PurposeObjectMotherSigV2

// Object Sigs
const PurposeObjectSigV0 = internal.PurposeObjectSigV0
const PurposeObjectSigV1 = internal.PurposeObjectSigV1
const PurposeObjectSigV2 = internal.PurposeObjectSigV2

// Papi signature purposes (jointly owned with amarbel-llc/papi; RFC
// 0002 §6.1, RFC-0001 §9–§10). Both carry a slot-9A ECDSA-P256
// (ecdsa-sha2-nistp256) signature as the 64-byte r‖s payload once
// SSH-wire framing is stripped, registered under PurposeTypePapiSig:
//
//	papi-doc-sig-v1   — over a PAPI document's canonicalized (JCS)
//	                    bytes (§10.2).
//	papi-proof-sig-v1 — over a PAPI identity-proof claim string
//	                    (§9.3 fmt="signature").
//
// MOVE-DOWN (piggy#186): papi is a DOWNSTREAM consumer of piggy's
// markl. These purposes live here transitionally (piggy is the
// canonical holder + joint owner); once papi depends on piggy's
// published markl module they move down to papi, which registers its
// own purposes consumer-side via RegisterPurpose (ADR 0006). The wire
// strings stay stable across the move.
// keep sorted
const PurposePapiDocSigV1 = internal.PurposePapiDocSigV1
const PurposePapiProofSigV1 = internal.PurposePapiProofSigV1

// Piggy keys (jointly owned with amarbel-llc/piggy; see RFC 0002 §6.1
// and the piggy-markl crate). The piggy-piv_* purposes carry a PIV
// slot's SSH-suitable public key; piggy-recipient-v1 carries an
// encryption recipient pubkey (PIV slot 9D or an age recipient).
// keep sorted
const PurposePiggyPivAuthV1 = internal.PurposePiggyPivAuthV1
const PurposePiggyPivCardAuthV1 = internal.PurposePiggyPivCardAuthV1
const PurposePiggyPivSigV1 = internal.PurposePiggyPivSigV1
const PurposePiggyRecipientV1 = internal.PurposePiggyRecipientV1

// PrivateKeys
const PurposeRepoPrivateKeyV1 = internal.PurposeRepoPrivateKeyV1

// PubKeys
const PurposeRepoPubKeyV1 = internal.PurposeRepoPubKeyV1
const PurposeRequestAuthChallengeV1 = internal.PurposeRequestAuthChallengeV1

// Request Auth
const PurposeRequestAuthResponseV1 = internal.PurposeRequestAuthResponseV1
const PurposeRequestRepoSigV1 = internal.PurposeRequestRepoSigV1
const PurposeTypeBlobDigest = internal.PurposeTypeBlobDigest

// PurposeTypeDodderObjectSig was madder's PurposeTypeObjectSig; renamed
// under piggy#183 since its purpose VALUES are dodder-specific
// (dodder-object-sig-v2). Label-only — nothing branches on the byte.
const PurposeTypeDodderObjectSig = internal.PurposeTypeDodderObjectSig
const PurposeTypeObjectDigest = internal.PurposeTypeObjectDigest
const PurposeTypeObjectMotherSig = internal.PurposeTypeObjectMotherSig

// PurposeTypePapiSig — the amarbel-llc/papi signature purposes
// (papi-doc-sig-v1, papi-proof-sig-v1). Distinct from the dodder
// object-sig type per Sasha's taxonomy ruling (#183). madder's
// papi-doc-sig-v1 landed under ObjectSig; piggy, as the canonical
// holder, overrides it to this dedicated type. Transitional — moves
// down to papi with the papi purposes (#186).
const PurposeTypePapiSig = internal.PurposeTypePapiSig
const PurposeTypePrivateKey = internal.PurposeTypePrivateKey
const PurposeTypePubKey = internal.PurposeTypePubKey
const PurposeTypeRepoPubKey = internal.PurposeTypeRepoPubKey
const PurposeTypeRequestAuth = internal.PurposeTypeRequestAuth
const PurposeTypeUnknown = internal.PurposeTypeUnknown
const PurposeV5MetadataDigestWithoutTai = internal.PurposeV5MetadataDigestWithoutTai
const RelatedRoleDigest = internal.RelatedRoleDigest
const RelatedRoleMotherSig = internal.RelatedRoleMotherSig
const RelatedRolePublicKey = internal.RelatedRolePublicKey
