// Code generated by dagnabit (0.4.0+1494bcc); DO NOT EDIT.

package markl_registrations

import internal "github.com/amarbel-llc/piggy/go/markl/internal/charlie/markl_registrations"

// AllPurposes is the ordered list of piggy's own purpose registrations.
// Order is deterministic but consumers must not depend on it — registration
// is order-independent under markl's lazy Related validation (ADR 0006).
var AllPurposes = internal.AllPurposes
var EcdsaP256Verify = internal.EcdsaP256Verify

// EcdsaP384Verify mirrors EcdsaP256Verify for NIST P-384: a 49-byte
// SEC1-compressed public key, a 96-byte r‖s signature, and SHA-384.
// Backs the ssh_ecdsa_nistp384_pub format added for parity with the Rust
// piggy-markl (piggy#86).
var EcdsaP384Verify = internal.EcdsaP384Verify
var Ed25519GeneratePrivateKey = internal.Ed25519GeneratePrivateKey
var Ed25519GetPublicKey = internal.Ed25519GetPublicKey
var Ed25519Sign = internal.Ed25519Sign
var Ed25519Verify = internal.Ed25519Verify
var NonceGenerate = internal.NonceGenerate
var NonceGenerate32 = internal.NonceGenerate32

// piggy-piv_* — public keys from the PIV auth / signature / card-auth
// slots (9A / 9C / 9E), carried as SSH-suitable points: P-256 (33-byte
// compressed), Ed25519 (32-byte raw), or P-384 (49-byte compressed).
// The Ed25519 + P-384 forms are piggy#86 (madder's Go core had only
// the P-256 form).
var PurposePiggyPivAuthV1Opts = internal.PurposePiggyPivAuthV1Opts
var PurposePiggyPivCardAuthV1Opts = internal.PurposePiggyPivCardAuthV1Opts
var PurposePiggyPivSigV1Opts = internal.PurposePiggyPivSigV1Opts

// piggy-recipient-v1 — the encryption recipient pubkey (PIV slot 9D
// ECDH key, or an age recipient) piggy encrypts blobs to.
var PurposePiggyRecipientV1Opts = internal.PurposePiggyRecipientV1Opts
