// Code generated by dagnabit (0.3.3+8d3cce0); DO NOT EDIT.

package markl_registrations

import internal "github.com/amarbel-llc/piggy/go/markl/internal/charlie/markl_registrations"

var EcdsaP256Verify = internal.EcdsaP256Verify
var Ed25519GeneratePrivateKey = internal.Ed25519GeneratePrivateKey
var Ed25519GetPublicKey = internal.Ed25519GetPublicKey
var Ed25519Sign = internal.Ed25519Sign
var Ed25519Verify = internal.Ed25519Verify
var NonceGenerate = internal.NonceGenerate
var NonceGenerate32 = internal.NonceGenerate32
