// Code generated by dagnabit (0.4.1+f3ad3d5); DO NOT EDIT.

package age

import internal "github.com/amarbel-llc/piggy/go/internal/delta/age"

// AgeX25519Generate mints a fresh age x25519 identity and returns its
// raw 32-byte secret scalar (the bech32 AGE-SECRET-KEY- payload).
var AgeX25519Generate = internal.AgeX25519Generate

// AgeX25519GetIOWrapper builds an age IOWrapper that decrypts to the
// x25519 identity whose raw secret scalar is carried by private. The
// secret is re-encoded as an AGE-SECRET-KEY- bech32 string and handed to
// dewey/age. The age secret never leaves the process.
var AgeX25519GetIOWrapper = internal.AgeX25519GetIOWrapper

// TODO verify if this is correct
var AgeX25519GetPublicKey = internal.AgeX25519GetPublicKey

// RegisterAgeX25519SecFormat swaps the real age-backed Generate +
// GetIOWrapper over the core's erroring age_x25519_sec stub (idempotent
// via sync.Once). Fired at init() below — it needs no connected signer
// (the secret machinery is self-contained), matching madder's always-on
// age recipient before the dep-light split. Adapted from madder's direct
// formats-map registration to the exported markl.SwapFormat seam over the
// stub installed by the blank-imported markl_registrations.
var RegisterAgeX25519SecFormat = internal.RegisterAgeX25519SecFormat
