// Code generated by dagnabit (0.5.0+61aaadb); DO NOT EDIT.

package blech32

import internal "code.linenisgreat.com/piggy/go/internal/alfa/blech32"

// TODO make generic
type Value = internal.Value

// Decode decodes a Blech32 string. If the string is uppercase, the HRP
// will be uppercase.
var Decode = internal.Decode

// DecodeDataOnly decodes the data portion of a blech32 string — the
// payload plus its 6-character checksum, with no HRP. The checksum is
// verified against an empty HRP.
//
// Like every decode path it is lowercase-only (RFC 0011 §3.5) and does
// NOT mutate bites.
var DecodeDataOnly = internal.DecodeDataOnly

// DecodeString decodes a Blech32 string. If the string is uppercase, the HRP
// will be
// uppercase.
var DecodeString = internal.DecodeString

// DecodeWithHRPOverride verifies `body`'s blech32 checksum against
// `hrp` instead of the leading segment in `body`'s own
// `<inner-hrp>-<data>` shape, and on success returns the recovered
// inner HRP segment and the decoded data bytes.
//
// Used to recover a `(formatId, data)` pair from the legacy combined
// `<purpose>@<format>` markl-id wire form (RFC 0002 §9.1), briefly
// shipped between commits `8dc78c7` and the #159 revert (`fd53684`).
// The caller verifies under the combined HRP but receives the inner
// `<format>` HRP and recovered bytes so it can re-emit under the
// canonical split-HRP rule (RFC 0002 §3.3).
//
// Returns ok=false (with empty innerHRP and nil data) on any
// structural failure (mixed case, missing separator, charset
// violation, bit-conversion error) or checksum mismatch. This helper
// exists for diagnostic recovery only; callers that need precise
// failure categories use Decode.
//
// The function does not mutate `body`.
var DecodeWithHRPOverride = internal.DecodeWithHRPOverride

// Encode encodes the HRP and a bytes slice to Blech32. If the HRP is uppercase,
// the output will be uppercase.
var Encode = internal.Encode
var EncodeDataOnly = internal.EncodeDataOnly
var EncodeHRPAsData = internal.EncodeHRPAsData
var ErrEmptyHRP = internal.ErrEmptyHRP
var ErrInvalidChecksum = internal.ErrInvalidChecksum
var ErrMixedCase = internal.ErrMixedCase
var ErrSeparatorMissing = internal.ErrSeparatorMissing

// ErrUppercase signals an all-uppercase input. RFC 0011 §3.5
// (linenisgreat/madder#273 ruling 6) narrows bech32's
// all-lower-or-all-upper rule to LOWERCASE ONLY, so uppercase is now
// its own rejection rather than an accepted alternate spelling.
//
// Rationale worth keeping: bech32 permits uppercase to enable QR
// alphanumeric mode, but that mode's charset (0-9, A-Z, space,
// $%*+-./:) has no lowercase, no `@`, and no `_` — so a markl-id can
// never be QR-alphanumeric-encoded regardless of payload case. The
// uppercase allowance buys markl-ids nothing, and costs one spelling
// per identifier.
var ErrUppercase = internal.ErrUppercase
var MakeValue = internal.MakeValue
var MakeValueWithExpectedHRP = internal.MakeValueWithExpectedHRP

// VerifyChecksumWithHRPOverride checks the blech32 checksum of `body`
// against `hrp` instead of the leading segment in `body`'s own
// `<own-hrp>-<data>` shape. Used to verify a blech32 string against an
// alternate HRP shape — in particular, the legacy combined
// `<purpose>@<format>` form documented in RFC 0002 §9.1, briefly
// shipped between commits `8dc78c7` and the #159 revert (`fd53684`).
//
// Returns true iff `body` passes uniform-case, separator-position, and
// charset validations AND the polymod over (hrp-expand(hrp), data
// indices) yields 1. On any structural failure (mixed case, missing
// separator, charset violation) it returns false rather than a typed
// error — this helper exists for diagnostic re-verification only;
// callers that need precise failure categories use Decode.
//
// The function does not mutate `body`.
var VerifyChecksumWithHRPOverride = internal.VerifyChecksumWithHRPOverride
