// Code generated by dagnabit (0.6.2+9d069d9); DO NOT EDIT.

package domain_interfaces

import (
	internal "code.linenisgreat.com/piggy/go/internal/0/domain_interfaces"
	interfaces "code.linenisgreat.com/purse-first/libs/dewey/pkgs/interfaces"
)

type (
	DigestWriteMap                                                      = internal.DigestWriteMap
	FormatHash                                                          = internal.FormatHash
	Hash                                                                = internal.Hash
	Lock[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]]        = internal.Lock[KEY, KEY_PTR]
	LockMutable[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]] = internal.LockMutable[KEY, KEY_PTR]
	MarklFormat                                                         = internal.MarklFormat
	MarklFormatGetter                                                   = internal.MarklFormatGetter
	MarklId                                                             = internal.MarklId
	MarklIdGetter                                                       = internal.MarklIdGetter
	MarklIdMutable                                                      = internal.MarklIdMutable
)
