// Code generated by dagnabit (0.5.0+dace734); DO NOT EDIT.

package domain_interfaces

import (
	internal "code.linenisgreat.com/piggy/go/internal/0/domain_interfaces"
	interfaces "code.linenisgreat.com/purse-first/libs/dewey/pkgs/interfaces"
)

type DigestWriteMap = internal.DigestWriteMap
type FormatHash = internal.FormatHash
type Hash = internal.Hash
type Lock[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]] = internal.Lock[KEY, KEY_PTR]
type LockMutable[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]] = internal.LockMutable[KEY, KEY_PTR]
type MarklFormat = internal.MarklFormat
type MarklFormatGetter = internal.MarklFormatGetter
type MarklId = internal.MarklId
type MarklIdGetter = internal.MarklIdGetter
type MarklIdMutable = internal.MarklIdMutable
