//! `piggy pass generate [--no-symbols,-n] [--clip,-c] [--qrcode,-q]
//! [--in-place,-i | --force,-f] pass-name [pass-length]` — native
//! Rust port of `cmd_generate` in `src/piggy.sh` (Split B of #96).
//!
//! Flag rules (mirroring bash + the getopt block):
//!   - `-n` / `--no-symbols` swaps the charset to alnum-only.
//!   - `-q` / `--qrcode` and `-c` / `--clip` are mutually exclusive.
//!   - `-i` / `--in-place` and `-f` / `--force` are mutually exclusive.
//!   - At least one positional (`pass-name`), at most two (`pass-name
//!     pass-length`). Bash's `[[ $# -ne 2 && $# -ne 1 ]]` is exact.
//!
//! Generation strategy: the bash uses `LC_ALL=C tr -dc "$characters"
//! </dev/urandom`, a streaming rejection sampler over a POSIX
//! character class (`[:punct:][:alnum:]` or `[:alnum:]`). We mirror
//! the rejection sampler in pure Rust by precomputing the explicit
//! byte set for the character class and rejecting any non-member
//! byte read from `/dev/urandom`. This preserves the bash's
//! uniform-over-class output distribution (sampling alphabet uniformly
//! across 0..256 and discarding non-members), so a user who set
//! `PIGGY_CHARACTER_SET=[:punct:][:alnum:]` continues to see the
//! same distribution of generated bytes.
//!
//! In-place (`-i`) mode replaces only the first line: the bash
//! pipeline is
//! ```text
//! { echo "$pass"; piggy_decrypt "$passfile" | tail -n +2; } \
//!   | piggy_encrypt "$passfile_temp" "$PIGGY_IDS"
//! mv "$passfile_temp" "$passfile"  # on success
//! ```
//! We mirror by decrypting the prior plaintext, stripping the first
//! line in memory, prepending the new password + `\n`, and encrypting
//! to a sibling temp path that we rename over the live file on
//! success.

use std::io::{Cursor, IsTerminal as _, Read as _, Write as _};
use std::path::{Path, PathBuf};
use std::time::Duration;

use crate::crypt;
use crate::git_ops;
use crate::platform::clipboard::{self, ClipPlan, Env as ClipEnv, ProcessRunner};
use crate::platform::qrcode::{self, Env as QrEnv, Plan as QrPlan};
use crate::store::{find_piggy_ids, store_root};

const DEFAULT_GENERATED_LENGTH: usize = 25;
const DEFAULT_CLIP_TIME_SECS: u64 = 45;
const DEFAULT_CHARACTER_SET: &str = "[:punct:][:alnum:]";
const DEFAULT_CHARACTER_SET_NO_SYMBOLS: &str = "[:alnum:]";

/// Exit code conventions:
/// - 0: generated and stored
/// - 1: usage / sneaky-path / encrypt / IO / overwrite-declined
pub fn run(args: &[String]) -> i32 {
    let opts = match parse_args(args) {
        Ok(o) => o,
        Err(msg) => {
            eprintln!("{msg}");
            return 1;
        }
    };

    if let Some(reason) = sneaky_path_reason(&opts.path) {
        eprintln!("Error: You've attempted to pass a sneaky path to piggy ({reason}). Go home.");
        return 1;
    }

    let root = store_root();
    let passfile = root.join(format!("{}.ebox", opts.path));
    let parent = passfile.parent().unwrap_or(&root);
    if let Err(err) = std::fs::create_dir_all(parent) {
        eprintln!("piggy pass generate: create {}: {}", parent.display(), err);
        return 1;
    }

    let subfolder = path_parent_for_search(&opts.path);
    let piggy_ids = match find_piggy_ids(&root, &subfolder)
        .and_then(|p| crate::pigpen_pointer::resolve_piggy_ids_path(&p))
    {
        Ok(p) => p,
        Err(msg) => {
            eprintln!("Error: {msg}");
            return 1;
        }
    };

    if !opts.inplace
        && !opts.force
        && passfile.exists()
        && !confirm(&format!(
            "An entry already exists for {}. Overwrite it?",
            opts.path
        ))
    {
        return 1;
    }

    let charset_spec = if opts.no_symbols {
        std::env::var("PIGGY_CHARACTER_SET_NO_SYMBOLS")
            .unwrap_or_else(|_| DEFAULT_CHARACTER_SET_NO_SYMBOLS.to_string())
    } else {
        std::env::var("PIGGY_CHARACTER_SET").unwrap_or_else(|_| DEFAULT_CHARACTER_SET.to_string())
    };
    let alphabet = expand_charset(&charset_spec);
    if alphabet.is_empty() {
        eprintln!("Error: pass-length character set \"{charset_spec}\" expanded to no characters.");
        return 1;
    }
    let pass = match generate_password(opts.length, &alphabet) {
        Ok(p) => p,
        Err(err) => {
            eprintln!("{err}");
            return 1;
        }
    };

    let result = if opts.inplace {
        encrypt_in_place(&piggy_ids, &passfile, &pass)
    } else {
        encrypt_fresh(&piggy_ids, &passfile, &pass)
    };
    if let Err(err) = result {
        eprintln!("piggy pass generate: {err}");
        return 1;
    }

    let verb = if opts.inplace { "Replace" } else { "Add" };
    if let Some(work_tree) = git_ops::find_inner_git_dir(&passfile, &root) {
        let _ = git_ops::add_and_commit(
            &work_tree,
            &passfile,
            &format!("{verb} generated password for {}.", opts.path),
        );
    }

    if opts.clip {
        return clip_password(pass.as_bytes(), &opts.path);
    }
    if opts.qrcode {
        return qrcode_password(pass.as_bytes(), &opts.path);
    }

    // The bash prints a bold-yellow `The generated password for <name>
    // is:` line followed by the password in bold yellow. We mirror
    // the ANSI escapes verbatim.
    print!(
        "\x1b[1mThe generated password for \x1b[4m{}\x1b[24m is:\x1b[0m\n\x1b[1m\x1b[93m{}\x1b[0m\n",
        opts.path, pass,
    );
    0
}

#[derive(Debug, PartialEq, Eq)]
struct Opts {
    path: String,
    length: usize,
    no_symbols: bool,
    qrcode: bool,
    clip: bool,
    force: bool,
    inplace: bool,
}

fn parse_args(args: &[String]) -> Result<Opts, String> {
    let mut no_symbols = false;
    let mut qrcode = false;
    let mut clip = false;
    let mut force = false;
    let mut inplace = false;
    let mut positional: Vec<String> = Vec::new();
    let mut iter = args.iter();
    let usage = "Usage: piggy pass generate [--no-symbols,-n] [--clip,-c] [--qrcode,-q] [--in-place,-i | --force,-f] pass-name [pass-length]";

    while let Some(arg) = iter.next() {
        let s = arg.as_str();
        if s == "--" {
            for rest in iter.by_ref() {
                positional.push(rest.clone());
            }
            break;
        } else if s == "-n" || s == "--no-symbols" {
            no_symbols = true;
        } else if s == "-q" || s == "--qrcode" {
            qrcode = true;
        } else if s == "-c" || s == "--clip" {
            clip = true;
        } else if s == "-f" || s == "--force" {
            force = true;
        } else if s == "-i" || s == "--in-place" {
            inplace = true;
        } else if s.starts_with('-') {
            return Err(usage.into());
        } else {
            positional.push(arg.clone());
        }
    }

    if force && inplace {
        return Err(usage.into());
    }
    if qrcode && clip {
        return Err(usage.into());
    }
    if positional.is_empty() || positional.len() > 2 {
        return Err(usage.into());
    }

    let path = positional[0].trim_end_matches('/').to_string();
    let length = match positional.get(1) {
        Some(raw) => parse_length(raw)?,
        None => env_length()?,
    };

    Ok(Opts {
        path,
        length,
        no_symbols,
        qrcode,
        clip,
        force,
        inplace,
    })
}

/// `$PIGGY_GENERATED_LENGTH` or 25, with the same "must be positive
/// integer" guard the bash applies to a CLI length argument.
fn env_length() -> Result<usize, String> {
    match std::env::var("PIGGY_GENERATED_LENGTH") {
        Ok(raw) if !raw.is_empty() => parse_length(&raw),
        _ => Ok(DEFAULT_GENERATED_LENGTH),
    }
}

fn parse_length(raw: &str) -> Result<usize, String> {
    // Bash: `[[ $length =~ ^[0-9]+$ ]]` then `[[ $length -gt 0 ]]`.
    if raw.is_empty() || !raw.bytes().all(|b| b.is_ascii_digit()) {
        return Err(format!("Error: pass-length \"{raw}\" must be a number."));
    }
    match raw.parse::<usize>() {
        Ok(0) => Err("Error: pass-length must be greater than zero.".into()),
        Ok(n) => Ok(n),
        Err(_) => Err(format!("Error: pass-length \"{raw}\" must be a number.")),
    }
}

fn confirm(message: &str) -> bool {
    let stdin = std::io::stdin();
    if !stdin.is_terminal() {
        return true;
    }
    let mut stderr = std::io::stderr();
    let _ = write!(stderr, "{message} [y/N] ");
    let _ = stderr.flush();
    let mut line = String::new();
    match stdin.lock().read_line(&mut line) {
        Ok(_) => {
            let trimmed = line.trim();
            trimmed == "y" || trimmed == "Y"
        }
        Err(_) => false,
    }
}

use std::io::BufRead as _;

/// Expand a POSIX character-class spec the way `LC_ALL=C tr -dc` does
/// for the two values piggy uses (`[:punct:][:alnum:]` and
/// `[:alnum:]`). We do NOT implement general POSIX bracket-expression
/// parsing — the bash only ever drives this with concatenations of
/// `[:punct:]`, `[:alpha:]`, `[:alnum:]`, `[:digit:]`, `[:lower:]`,
/// `[:upper:]`, and literal printable ASCII characters. Anything
/// outside that shape is treated as a literal byte.
///
/// The byte sets here match POSIX C-locale semantics:
/// - `:alnum:` = `[A-Za-z0-9]`
/// - `:alpha:` = `[A-Za-z]`
/// - `:digit:` = `[0-9]`
/// - `:lower:` = `[a-z]`
/// - `:upper:` = `[A-Z]`
/// - `:punct:` = `[!"#$%&'()*+,\-./:;<=>?@\[\\\]^_`{|}~]` (ASCII 33-126
///   minus alnum and space, per POSIX/C `ispunct`).
fn expand_charset(spec: &str) -> Vec<u8> {
    let mut set = std::collections::BTreeSet::new();
    let bytes = spec.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'[' && i + 1 < bytes.len() && bytes[i + 1] == b':' {
            // Find the closing `:]`.
            if let Some(end) = find_subseq(&bytes[i + 2..], b":]") {
                let class_name = &bytes[i + 2..i + 2 + end];
                add_class(class_name, &mut set);
                i = i + 2 + end + 2;
                continue;
            }
        }
        set.insert(bytes[i]);
        i += 1;
    }
    set.into_iter().collect()
}

fn find_subseq(hay: &[u8], needle: &[u8]) -> Option<usize> {
    hay.windows(needle.len()).position(|w| w == needle)
}

fn add_class(name: &[u8], set: &mut std::collections::BTreeSet<u8>) {
    let class = std::str::from_utf8(name).unwrap_or("");
    match class {
        "alnum" => add_range_inclusive(b'a', b'z', set)
            .and(add_range_inclusive(b'A', b'Z', set))
            .and(add_range_inclusive(b'0', b'9', set)),
        "alpha" => add_range_inclusive(b'a', b'z', set).and(add_range_inclusive(b'A', b'Z', set)),
        "digit" => add_range_inclusive(b'0', b'9', set),
        "lower" => add_range_inclusive(b'a', b'z', set),
        "upper" => add_range_inclusive(b'A', b'Z', set),
        "punct" => {
            for b in 33u8..=126u8 {
                if !is_alnum(b) && b != b' ' {
                    set.insert(b);
                }
            }
            Some(())
        }
        _ => Some(()),
    }
    .unwrap_or(());
}

fn add_range_inclusive(lo: u8, hi: u8, set: &mut std::collections::BTreeSet<u8>) -> Option<()> {
    for b in lo..=hi {
        set.insert(b);
    }
    Some(())
}

fn is_alnum(b: u8) -> bool {
    b.is_ascii_alphanumeric()
}

/// Streaming rejection sampler. Read from `/dev/urandom` byte by
/// byte; keep each byte that is in `alphabet`. Stop once `length`
/// bytes are accepted. Errors out only on actual IO failure or if
/// the read returns 0 bytes (EOF — would have to mean `/dev/urandom`
/// was redirected).
fn generate_password(length: usize, alphabet: &[u8]) -> Result<String, String> {
    let mut file = std::fs::File::open("/dev/urandom")
        .map_err(|e| format!("Could not open /dev/urandom: {e}"))?;
    let mut buf = [0u8; 4096];
    let mut out = Vec::with_capacity(length);
    let alphabet_set: std::collections::BTreeSet<u8> = alphabet.iter().copied().collect();
    while out.len() < length {
        let n = file
            .read(&mut buf)
            .map_err(|e| format!("Could not generate password from /dev/urandom: {e}"))?;
        if n == 0 {
            return Err("Could not generate password from /dev/urandom.".into());
        }
        for &b in &buf[..n] {
            if alphabet_set.contains(&b) {
                out.push(b);
                if out.len() == length {
                    break;
                }
            }
        }
    }
    // Every accepted byte is in alphabet (which is ASCII), so
    // from_utf8 cannot fail.
    Ok(String::from_utf8(out).expect("alphabet is ASCII"))
}

/// Encrypt a fresh ebox: pipe `<pass>\n` through `crypt::encrypt`
/// straight at `$passfile`. The bash uses `echo "$pass" |
/// piggy_encrypt`, which appends a single newline; mirror.
fn encrypt_fresh(piggy_ids: &Path, passfile: &Path, pass: &str) -> Result<(), String> {
    let mut input = Vec::with_capacity(pass.len() + 1);
    input.extend_from_slice(pass.as_bytes());
    input.push(b'\n');
    crypt::encrypt(piggy_ids, passfile, Cursor::new(input))
}

/// In-place replace: decrypt the existing file, drop its first line,
/// prepend `<pass>\n`, encrypt to a sibling tempfile, then atomically
/// rename over the live file. The bash uses `mv $passfile_temp
/// $passfile`; the rename is the same atomic op.
fn encrypt_in_place(piggy_ids: &Path, passfile: &Path, pass: &str) -> Result<(), String> {
    let prior =
        crypt::decrypt(passfile).map_err(|err| format!("decrypt existing passfile: {err}"))?;
    let mut new_plaintext = Vec::with_capacity(prior.len() + pass.len() + 1);
    new_plaintext.extend_from_slice(pass.as_bytes());
    new_plaintext.push(b'\n');
    new_plaintext.extend_from_slice(drop_first_line(&prior));

    let temp = sibling_temp_path(passfile);
    match crypt::encrypt(piggy_ids, &temp, Cursor::new(new_plaintext)) {
        Ok(()) => {}
        Err(err) => {
            let _ = std::fs::remove_file(&temp);
            return Err(format!("Could not reencrypt new password: {err}"));
        }
    }
    std::fs::rename(&temp, passfile)
        .map_err(|err| format!("rename {} -> {}: {err}", temp.display(), passfile.display()))
}

/// `tail -n +2` — return the bytes after the first `\n` (inclusive of
/// the second line onwards). If the input has no newline at all,
/// return an empty slice (tail -n +2 on a single-line file emits
/// nothing).
fn drop_first_line(bytes: &[u8]) -> &[u8] {
    match bytes.iter().position(|b| *b == b'\n') {
        Some(idx) => &bytes[idx + 1..],
        None => &[],
    }
}

/// Sibling temp path: `${passfile}.tmp.<rand>.<rand>.<rand>.<rand>.--`.
/// The bash uses four `$RANDOM` slots; we use a single longer suffix
/// since the determinism is the same.
fn sibling_temp_path(passfile: &Path) -> PathBuf {
    let mut name = passfile
        .file_name()
        .map(std::ffi::OsStr::to_os_string)
        .unwrap_or_else(|| std::ffi::OsString::from("piggy-tmp"));
    name.push(format!(".tmp.{}.{}.--", std::process::id(), nanos()));
    passfile.with_file_name(name)
}

fn nanos() -> u128 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0)
}

fn path_parent_for_search(path: &str) -> String {
    let p = PathBuf::from(path);
    match p.parent() {
        Some(parent) if !parent.as_os_str().is_empty() => parent.to_string_lossy().into_owned(),
        _ => String::new(),
    }
}

fn sneaky_path_reason(path: &str) -> Option<&'static str> {
    for component in Path::new(path).components() {
        if matches!(component, std::path::Component::ParentDir) {
            return Some("`..` component");
        }
    }
    None
}

/// Push `pass` to the clipboard and spawn the deferred-restore worker.
/// Mirrors `show -c`'s code path (Split A) so we share the same
/// behavior across the two `--clip`-bearing pass-style handlers.
fn clip_password(pass: &[u8], name: &str) -> i32 {
    let env = ClipEnv::from_process();
    let clip_time = Duration::from_secs(clip_time_seconds());
    let plan = match clipboard::copy_with_clear(&env, pass, name, clip_time, &ProcessRunner) {
        Ok(p) => p,
        Err(err) => {
            eprintln!("{err}");
            return 1;
        }
    };
    if let Err(err) = spawn_clipboard_restore_worker(&plan) {
        eprintln!("piggy pass generate: spawn restore worker: {err}");
    }
    println!("{}", plan.user_message);
    0
}

fn qrcode_password(pass: &[u8], name: &str) -> i32 {
    let env = QrEnv::from_process();
    let plan = qrcode::render_plan(&env, name);
    match plan {
        QrPlan::Gui {
            viewer,
            viewer_args,
        } => spawn_qrcode_gui(viewer, &viewer_args, pass),
        QrPlan::Stdout => spawn_qrcode_stdout(pass),
    }
}

fn spawn_qrcode_gui(viewer: &str, args: &[std::ffi::OsString], pass: &[u8]) -> i32 {
    use std::process::{Command, Stdio};
    let mut qrencode = match Command::new("qrencode")
        .arg("--size")
        .arg("10")
        .arg("-o")
        .arg("-")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
    {
        Ok(c) => c,
        Err(err) => {
            eprintln!("piggy pass generate: spawn qrencode: {err}");
            return 1;
        }
    };
    if let Some(mut stdin) = qrencode.stdin.take() {
        if let Err(err) = stdin.write_all(pass) {
            eprintln!("piggy pass generate: write to qrencode: {err}");
            return 1;
        }
    }
    let qr_stdout = match qrencode.stdout.take() {
        Some(s) => s,
        None => {
            eprintln!("piggy pass generate: qrencode stdout unavailable");
            return 1;
        }
    };
    let viewer_status = Command::new(viewer).args(args).stdin(qr_stdout).status();
    let _ = qrencode.wait();
    match viewer_status {
        Ok(s) if s.success() => 0,
        Ok(s) => s.code().unwrap_or(1),
        Err(err) => {
            eprintln!("piggy pass generate: spawn {viewer}: {err}");
            1
        }
    }
}

fn spawn_qrcode_stdout(pass: &[u8]) -> i32 {
    use std::process::{Command, Stdio};
    let mut child = match Command::new("qrencode")
        .arg("-t")
        .arg("utf8")
        .stdin(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
    {
        Ok(c) => c,
        Err(err) => {
            eprintln!("piggy pass generate: spawn qrencode: {err}");
            return 1;
        }
    };
    if let Some(mut stdin) = child.stdin.take() {
        if let Err(err) = stdin.write_all(pass) {
            eprintln!("piggy pass generate: write to qrencode: {err}");
            return 1;
        }
    }
    match child.wait() {
        Ok(s) if s.success() => 0,
        Ok(s) => s.code().unwrap_or(1),
        Err(err) => {
            eprintln!("piggy pass generate: wait qrencode: {err}");
            1
        }
    }
}

/// Mirrors `show::spawn_clipboard_restore_worker`. We can't share the
/// helper across modules without exposing it in a sibling; both
/// handlers do the same `internal-clipboard-restore` rename + stdin
/// serialize + detach dance.
fn spawn_clipboard_restore_worker(plan: &ClipPlan) -> std::io::Result<()> {
    use std::os::unix::process::CommandExt as _;
    use std::process::{Command, Stdio};
    let piggy_bin = std::env::current_exe().or_else(|_| {
        std::env::var_os("PIGGY_BIN")
            .map(std::path::PathBuf::from)
            .ok_or_else(|| std::io::Error::other("current_exe unavailable and PIGGY_BIN unset"))
    })?;
    let mut cmd = Command::new(&piggy_bin);
    cmd.arg("internal-clipboard-restore");
    cmd.arg0(&plan.sleep_argv0);
    cmd.stdin(Stdio::piped());
    cmd.stdout(Stdio::null());
    cmd.stderr(Stdio::null());

    let mut child = cmd.spawn()?;
    {
        let mut stdin = child
            .stdin
            .take()
            .ok_or_else(|| std::io::Error::other("restore worker stdin unavailable"))?;
        let bytes = crate::internal_clipboard_restore::serialize_plan(plan);
        stdin.write_all(&bytes)?;
    }
    std::mem::drop(child);
    Ok(())
}

fn clip_time_seconds() -> u64 {
    std::env::var("PIGGY_CLIP_TIME")
        .ok()
        .and_then(|s| s.parse::<u64>().ok())
        .unwrap_or(DEFAULT_CLIP_TIME_SECS)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn s(v: &[&str]) -> Vec<String> {
        v.iter().map(|x| x.to_string()).collect()
    }

    #[test]
    fn parse_args_requires_pass_name() {
        assert!(parse_args(&s(&[])).is_err());
    }

    #[test]
    fn parse_args_defaults() {
        let o = parse_args(&s(&["cred1"])).unwrap();
        assert_eq!(o.path, "cred1");
        assert_eq!(o.length, DEFAULT_GENERATED_LENGTH);
        assert!(!o.no_symbols);
        assert!(!o.qrcode);
        assert!(!o.clip);
        assert!(!o.force);
        assert!(!o.inplace);
    }

    #[test]
    fn parse_args_accepts_length() {
        let o = parse_args(&s(&["cred1", "32"])).unwrap();
        assert_eq!(o.length, 32);
    }

    #[test]
    fn parse_args_rejects_non_numeric_length() {
        let err = parse_args(&s(&["cred1", "abc"])).unwrap_err();
        assert!(err.contains("must be a number"), "got: {err}");
    }

    #[test]
    fn parse_args_rejects_zero_length() {
        let err = parse_args(&s(&["cred1", "0"])).unwrap_err();
        assert!(err.contains("greater than zero"), "got: {err}");
    }

    #[test]
    fn parse_args_rejects_too_many_positionals() {
        let err = parse_args(&s(&["a", "1", "extra"])).unwrap_err();
        assert!(err.contains("Usage"), "got: {err}");
    }

    #[test]
    fn parse_args_flags_short_and_long() {
        let o = parse_args(&s(&["-n", "--clip", "cred1"])).unwrap();
        assert!(o.no_symbols);
        assert!(o.clip);
    }

    #[test]
    fn parse_args_inplace_force_mutex() {
        let err = parse_args(&s(&["-i", "-f", "cred1"])).unwrap_err();
        assert!(err.contains("Usage"), "got: {err}");
    }

    #[test]
    fn parse_args_qrcode_clip_mutex() {
        let err = parse_args(&s(&["-q", "-c", "cred1"])).unwrap_err();
        assert!(err.contains("Usage"), "got: {err}");
    }

    #[test]
    fn parse_args_trims_trailing_slash_from_path() {
        let o = parse_args(&s(&["folder/sub/"])).unwrap();
        assert_eq!(o.path, "folder/sub");
    }

    #[test]
    fn parse_args_double_dash_terminates() {
        let o = parse_args(&s(&["--", "cred1", "12"])).unwrap();
        assert_eq!(o.path, "cred1");
        assert_eq!(o.length, 12);
    }

    #[test]
    fn parse_args_rejects_unknown_flag() {
        let err = parse_args(&s(&["--bogus", "cred1"])).unwrap_err();
        assert!(err.contains("Usage"), "got: {err}");
    }

    #[test]
    fn expand_charset_alnum_is_62_chars() {
        let chars = expand_charset("[:alnum:]");
        assert_eq!(chars.len(), 26 + 26 + 10);
        for c in b'a'..=b'z' {
            assert!(chars.contains(&c));
        }
        for c in b'0'..=b'9' {
            assert!(chars.contains(&c));
        }
    }

    #[test]
    fn expand_charset_punct_alnum_includes_punct() {
        let chars = expand_charset("[:punct:][:alnum:]");
        assert!(chars.contains(&b'!'));
        assert!(chars.contains(&b'@'));
        assert!(chars.contains(&b'~'));
        // alnum still in there
        assert!(chars.contains(&b'a'));
        // space NOT included
        assert!(!chars.contains(&b' '));
        // control bytes not included
        assert!(!chars.contains(&0x01));
    }

    #[test]
    fn expand_charset_literal_bytes_pass_through() {
        let chars = expand_charset("abc[:digit:]");
        assert!(chars.contains(&b'a'));
        assert!(chars.contains(&b'b'));
        assert!(chars.contains(&b'c'));
        assert!(chars.contains(&b'5'));
    }

    #[test]
    fn generate_password_length_matches_alphabet_only() {
        // Drive with an alphabet that includes only the ASCII digits
        // 0..9 — the rejection sampler should still produce a length-N
        // string drawn from those.
        let alphabet: Vec<u8> = (b'0'..=b'9').collect();
        let pass = generate_password(20, &alphabet).unwrap();
        assert_eq!(pass.len(), 20);
        for c in pass.bytes() {
            assert!(c.is_ascii_digit(), "non-digit byte: {c}");
        }
    }

    #[test]
    fn generate_password_with_full_punct_alnum() {
        let alphabet = expand_charset("[:punct:][:alnum:]");
        let pass = generate_password(64, &alphabet).unwrap();
        assert_eq!(pass.len(), 64);
        for c in pass.bytes() {
            assert!(alphabet.contains(&c), "byte {c:#x} not in alphabet");
        }
    }

    #[test]
    fn drop_first_line_strips_through_first_newline() {
        assert_eq!(drop_first_line(b"first\nsecond\nthird"), b"second\nthird");
        assert_eq!(drop_first_line(b"first\n"), b"");
        assert_eq!(drop_first_line(b"only-line-no-nl"), b"");
        assert_eq!(drop_first_line(b""), b"");
    }

    #[test]
    fn sibling_temp_path_is_in_same_dir() {
        let tmp = sibling_temp_path(Path::new("/store/x/cred1.ebox"));
        assert_eq!(tmp.parent(), Some(Path::new("/store/x")));
        assert!(
            tmp.file_name()
                .and_then(|s| s.to_str())
                .is_some_and(|s| s.starts_with("cred1.ebox.tmp.") && s.ends_with(".--")),
            "unexpected tmp name: {tmp:?}"
        );
    }

    #[test]
    fn sneaky_path_rejects_parent() {
        assert!(sneaky_path_reason("../etc").is_some());
        assert!(sneaky_path_reason("a/../b").is_some());
    }

    #[test]
    fn sneaky_path_accepts_normal() {
        assert!(sneaky_path_reason("a/b").is_none());
    }
}
