// Code generated by dagnabit (0.4.1+dirty); DO NOT EDIT.

package pigpen

import internal "github.com/amarbel-llc/piggy/go/internal/delta/pigpen"

// Document is the in-memory model of a pigpen-v1 document.
type Document = internal.Document

// ECDHOracle performs the card-bound scalar multiplication for a P-256
// recipient (RFC 0008 §4.3, §7). A WASM host wires this to piggy-agent's
// ecdh@joyent.com extension; the slot-9D scalar never leaves the card.
type ECDHOracle = internal.ECDHOracle

// Recipient is one recipient line of a pigpen document.
type Recipient = internal.Recipient

// X25519Identity is a software age identity for the pure-software open
// path (RFC 0008 §4.4): both halves of an X25519 keypair.
type X25519Identity = internal.X25519Identity

// NewRecipientSet builds a payload-less pigpen document — the drop-in for
// a piggy-ids file (RFC 0008 §2.2).
var NewRecipientSet = internal.NewRecipientSet

// ParseDocument decodes a pigpen document from hyphence bytes.
var ParseDocument = internal.ParseDocument

// Seal encrypts plaintext to the given recipients, producing a sealed
// pigpen document. All wraps are computed in pure software (the P-256
// encrypt side needs no card). rng may be nil to use the package CSPRNG.
var Seal = internal.Seal
