// Code generated by dagnabit (0.6.2+9d069d9); DO NOT EDIT.

package pigpen

import internal "code.linenisgreat.com/piggy/go/internal/delta/pigpen"

// Document is the in-memory model of a pigpen-v1 document.
type Document = internal.Document

// ECDHOracle performs the card-bound scalar multiplication for a P-256
// recipient (RFC 0008 §4.3, §7). A WASM host wires this to piggy-agent's
// ecdh@joyent.com extension; the slot-9D scalar never leaves the card.
type ECDHOracle = internal.ECDHOracle

// Pointer is the pointer face of a pigpen document (RFC 0008 §2.2): it
// names a resolver by kind and an opaque locator instead of carrying
// recipients. Locator is never interpreted here; it is handed verbatim to
// whatever runs the resolver (RFC 0010).
type Pointer = internal.Pointer

// Recipient is one recipient line of a pigpen document.
type Recipient = internal.Recipient

// X25519Identity is a software age identity for the pure-software open
// path (RFC 0008 §4.4): both halves of an X25519 keypair.
type X25519Identity = internal.X25519Identity

// CanonicalRecipientSet returns the bytes a consumer hashes to detect a
// changed recipient set: each id in its piggy-recipient-v1@ text form,
// de-duplicated, sorted bytewise, one per line, each line ending in "\n".
// The empty set is zero bytes. Ids that are not encryption recipients are
// ignored. Comments and order never reach this form, which makes it RFC
// 0003 equality.
var CanonicalRecipientSet = internal.CanonicalRecipientSet

// NewRecipientSet builds a payload-less pigpen document — the drop-in for
// a piggy-ids file (RFC 0008 §2.2).
var NewRecipientSet = internal.NewRecipientSet

// ParseDocument decodes a pigpen document from hyphence bytes.
var ParseDocument = internal.ParseDocument

// ParsePointer decodes a pigpen-pointer-v1 document. A document of any
// other type, a pointer missing its kind or locator, and a pointer
// carrying any other `-` line (a recipient, say) are all errors.
var ParsePointer = internal.ParsePointer

// ParseRecipients reads a piggy-ids file in either form and returns its
// encryption recipients: a pigpen document (leading "---\n", RFC 0009
// §3.2) or RFC 0003 lines. A pointer document is an error here; resolve
// it first (RFC 0010).
var ParseRecipients = internal.ParseRecipients

// SameRecipientSet reports whether a and b name the same encryption
// recipients: exactly equality of their CanonicalRecipientSet bytes.
var SameRecipientSet = internal.SameRecipientSet

// Seal encrypts plaintext to the given recipients, producing a sealed
// pigpen document. All wraps are computed in pure software (the P-256
// encrypt side needs no card). rng may be nil to use the package CSPRNG.
//
// A caller-supplied rng does NOT make the output reproducible: the file
// key and payload nonce are read from it, but crypto/ecdh generates the
// per-recipient ephemeral keys from the system CSPRNG regardless
// (measured on go 1.26). Supply an rng only as an entropy source.
var Seal = internal.Seal

// ValidatePointerKind enforces RFC 0010 §2's one constraint on a kind: it
// names an executable looked up on PATH, so it must not be empty and must
// not contain a path separator or a NUL byte.
var ValidatePointerKind = internal.ValidatePointerKind
