// Code generated by dagnabit (0.6.2+9d069d9); DO NOT EDIT.

package pigpen_resolve

import internal "code.linenisgreat.com/piggy/go/internal/echo/pigpen_resolve"

// IsPointer reports whether raw is a hyphence document whose type line
// names the pointer face. It does not validate the pointer.
var IsPointer = internal.IsPointer

// LoadRecipients returns the encryption recipients a piggy-ids file
// names, whichever of its three forms it takes: RFC 0003 lines, a pigpen
// recipient-set (or sealed) document, or a pointer, which is resolved
// with Resolve.
var LoadRecipients = internal.LoadRecipients

// Resolve runs `pigpen-resolver-<kind> resolve <locator>` and parses its
// stdout as a recipient-set pigpen document (RFC 0010 §3).
//
// Failure is hard (§5): a missing resolver, a non-zero exit, and output
// that is not a recipient set are all errors, and each names the pointer's
// kind and locator. There is no cache and no stale fallback. The resolver
// runs under ctx; give it a deadline.
//
// The resolved bytes are trusted exactly as far as the resolver binary on
// PATH is (§6): this package verifies no signature and interprets no
// locator.
var Resolve = internal.Resolve
