//go:build test && pigpen_vectors_generate

package pigpen

// To regenerate docs/rfcs/0008-pigpen-vectors.txt, run:
//
//	just codemod-pigpen-vectors
//
// The default test suite never invokes this generator. The committed file
// is the normative artifact; TestNormativePigpenVectors replays every
// record on every run, and the Rust crate replays the same file. Every
// secret below is a fixed, public test value.

import (
	"bytes"
	"crypto/ecdh"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"code.linenisgreat.com/piggy/go/internal/alfa/blech32"
	"code.linenisgreat.com/piggy/go/internal/bravo/markl"
)

const pigpenVectorsHeader = `# pigpen-v1 normative test vectors.
#
# Normative for piggy RFC 0008 (see its "Conformance" section) per RFC 0009
# section 8. Both reference implementations replay this one file:
#   go/internal/delta/pigpen/vectors_test.go
#   crates/piggy-pigpen/tests/vectors.rs
# GENERATED by "just codemod-pigpen-vectors"; do not edit by hand.
#
# Records are separated by blank lines. Each line is "key: value". Values
# are lowercase hex unless noted. Lists are space-separated.
#
#   name               record name
#   outcome            open | normalize | recipient-set | reject
#   document           the complete document bytes
#   document-sha256    SHA-256 of the document, used INSTEAD of "document"
#                      when the document is large; the document is then the
#                      output of sealing with the record's inputs
#   normalized         (normalize) the bytes a reader re-serializes to
#   stage              (reject) parse | open: where the document must fail
#   plaintext          the sealed plaintext
#   plaintext-zeros    decimal count of zero bytes, INSTEAD of "plaintext"
#   recipients         markl ids, in document order (text, not hex)
#   file-key           16-byte file key (RFC 0008 section 4.1)
#   payload-nonce      16-byte payload nonce (section 4.5)
#   ephemeral-secrets  one ephemeral private scalar per recipient, in
#                      recipient order: a 32-byte X25519 secret, or a
#                      32-byte big-endian P-256 scalar
#   x25519-secrets     X25519 identity secrets to open with
#   p256-secret        P-256 identity scalar to open with; stands in for
#                      the card behind the ECDH oracle
#
# An "open" record with seal inputs must reproduce its document exactly
# when sealed with them, must re-serialize unchanged after a parse, and
# must open to its plaintext. Every secret here is a public test value.
`

type vectorWriter struct {
	out bytes.Buffer
}

func (w *vectorWriter) record(fields ...string) {
	if len(fields)%2 != 0 {
		panic("vectorWriter.record: odd field list")
	}
	w.out.WriteByte('\n')
	for i := 0; i < len(fields); i += 2 {
		fmt.Fprintf(&w.out, "%s: %s\n", fields[i], fields[i+1])
	}
}

func hexList(secrets ...[]byte) string {
	parts := make([]string, len(secrets))
	for i, s := range secrets {
		parts[i] = hex.EncodeToString(s)
	}
	return strings.Join(parts, " ")
}

func idList(ids ...markl.Id) string {
	parts := make([]string, len(ids))
	for i, id := range ids {
		parts[i] = id.StringWithFormat()
	}
	return strings.Join(parts, " ")
}

func mustID(t *testing.T, purpose, format string, data []byte) markl.Id {
	t.Helper()
	var id markl.Id
	if err := id.SetPurposeId(purpose); err != nil {
		t.Fatal(err)
	}
	if err := id.SetMarklId(format, data); err != nil {
		t.Fatalf("%s@%s: %v", purpose, format, err)
	}
	return id
}

func mustBlech32(t *testing.T, hrp string, data []byte) string {
	t.Helper()
	out, err := blech32.Encode(hrp, data)
	if err != nil {
		t.Fatal(err)
	}
	return string(out)
}

func replaceOnce(t *testing.T, raw []byte, old, replacement string) []byte {
	t.Helper()
	if !bytes.Contains(raw, []byte(old)) {
		t.Fatalf("%q not found in the base document", old)
	}
	return bytes.Replace(raw, []byte(old), []byte(replacement), 1)
}

func TestGeneratePigpenVectors(t *testing.T) {
	// --- fixed public test secrets --------------------------------------
	xSecret := fixedBytes(32, 0x01) // the x25519 identity of the #210 interop vectors
	pSecret := fixedP256Scalar(0x30)
	fileKey := fixedBytes(fileKeyLen, 0x10)
	nonce := fixedBytes(payloadNonceLen, 0x40)
	xEphemeral := fixedBytes(32, 0x70)
	pEphemeral := fixedP256Scalar(0xa0)

	xKey, err := ecdh.X25519().NewPrivateKey(xSecret)
	if err != nil {
		t.Fatal(err)
	}
	pKey, err := ecdh.P256().NewPrivateKey(pSecret)
	if err != nil {
		t.Fatal(err)
	}
	pCompressed, err := p256Compress(pKey.PublicKey().Bytes())
	if err != nil {
		t.Fatal(err)
	}

	xID := mustID(t, purposeRecipient, formatAgeX25519, xKey.PublicKey().Bytes())
	pID := mustID(t, purposeRecipient, formatPivyP256, pCompressed)
	sshAuthID := mustID(t, markl.PurposePiggyPivAuthV1, markl.FormatIdSshEd25519Pub, fixedBytes(32, 0xc0))
	foreignSigID := mustID(t, "papi-pigpen-self-sig-v1", markl.FormatIdEcdsaP256Sig, fixedBytes(64, 0xd0))

	seal := func(plaintext []byte, recipients []markl.Id, ephemeral ...[]byte) (*Document, []byte) {
		t.Helper()
		doc, err := sealWith(plaintext, recipients, sealInputs{
			fileKey:      bytes.Clone(fileKey),
			payloadNonce: bytes.Clone(nonce),
			ephemeral:    ephemeral,
		})
		if err != nil {
			t.Fatal(err)
		}
		wire, err := doc.MarshalText()
		if err != nil {
			t.Fatal(err)
		}
		return doc, wire
	}

	w := &vectorWriter{}
	w.out.WriteString(pigpenVectorsHeader)

	sealed := func(name string, plaintext []byte, recipients []markl.Id, ephemeral [][]byte, opener ...string) []byte {
		t.Helper()
		_, wire := seal(plaintext, recipients, ephemeral...)
		fields := []string{
			"name", name,
			"outcome", "open",
			"recipients", idList(recipients...),
			"file-key", hex.EncodeToString(fileKey),
			"payload-nonce", hex.EncodeToString(nonce),
			"ephemeral-secrets", hexList(ephemeral...),
		}
		fields = append(fields, opener...)
		fields = append(fields,
			"plaintext", hex.EncodeToString(plaintext),
			"document", hex.EncodeToString(wire),
		)
		w.record(fields...)
		return wire
	}

	xOpener := []string{"x25519-secrets", hex.EncodeToString(xSecret)}
	pOpener := []string{"p256-secret", hex.EncodeToString(pSecret)}

	// --- sealed documents ------------------------------------------------
	plaintext := []byte("pigpen-v1 normative vector")
	xWire := sealed("sealed/x25519", plaintext, []markl.Id{xID}, [][]byte{xEphemeral}, xOpener...)
	sealed("sealed/p256", plaintext, []markl.Id{pID}, [][]byte{pEphemeral}, pOpener...)
	sealed("sealed/x25519-and-p256/opened-with-x25519", plaintext,
		[]markl.Id{xID, pID}, [][]byte{xEphemeral, pEphemeral}, xOpener...)
	bothWire := sealed("sealed/x25519-and-p256/opened-with-p256", plaintext,
		[]markl.Id{xID, pID}, [][]byte{xEphemeral, pEphemeral}, pOpener...)
	sealed("sealed/empty-plaintext", nil, []markl.Id{xID}, [][]byte{xEphemeral}, xOpener...)

	// One byte past a STREAM chunk: two chunks, the last holding one byte.
	twoChunks := make([]byte, streamChunkSize+1)
	_, twoChunksWire := seal(twoChunks, []markl.Id{xID}, xEphemeral)
	twoChunksDigest := sha256.Sum256(twoChunksWire)
	w.record(
		"name", "sealed/two-stream-chunks",
		"outcome", "open",
		"recipients", idList(xID),
		"file-key", hex.EncodeToString(fileKey),
		"payload-nonce", hex.EncodeToString(nonce),
		"ephemeral-secrets", hexList(xEphemeral),
		"x25519-secrets", hex.EncodeToString(xSecret),
		"plaintext-zeros", fmt.Sprint(len(twoChunks)),
		"document-sha256", hex.EncodeToString(twoChunksDigest[:]),
	)

	// The two #210 cross-language interop documents, sealed independently
	// by each implementation with ephemeral keys nobody recorded: they pin
	// that documents written before these vectors existed still open.
	for _, legacy := range []struct{ name, hexv string }{
		{"sealed/legacy-interop/sealed-by-rust", sealedByRust},
		{"sealed/legacy-interop/sealed-by-go", sealedByGo},
	} {
		w.record(
			"name", legacy.name,
			"outcome", "open",
			"x25519-secrets", hex.EncodeToString(xSecret),
			"plaintext", hex.EncodeToString([]byte(interopPlaintext)),
			"document", legacy.hexv,
		)
	}

	// --- accepted, re-serialized canonically -----------------------------
	wrapLock := " < " + markl.PurposePigpenWrapV1 + "@"
	w.record(
		"name", "normalize/quoted-wrap-purpose",
		"outcome", "normalize",
		"x25519-secrets", hex.EncodeToString(xSecret),
		"plaintext", hex.EncodeToString(plaintext),
		"document", hex.EncodeToString(replaceOnce(t, xWire, wrapLock, ` < "`+markl.PurposePigpenWrapV1+`"@`)),
		"normalized", hex.EncodeToString(xWire),
	)

	// --- recipient sets --------------------------------------------------
	recipientSet := func(name string, doc *Document) {
		t.Helper()
		wire, err := doc.MarshalText()
		if err != nil {
			t.Fatal(err)
		}
		w.record("name", name, "outcome", "recipient-set", "document", hex.EncodeToString(wire))
	}
	recipientSet("recipient-set/description-and-comments", &Document{
		Description: "recipients for a normative vector",
		Recipients: []Recipient{
			{ID: xID, Comment: "laptop < backup"},
			{ID: pID, Comment: "#1 yubikey (9D)"},
		},
	})
	recipientSet("recipient-set/with-non-encryption-lines", &Document{
		Recipients: []Recipient{
			{ID: pID},
			{ID: sshAuthID, Comment: "ssh login key, not an encryption recipient"},
			{ID: foreignSigID},
		},
	})
	w.record(
		"name", "recipient-set/legacy-interop",
		"outcome", "recipient-set",
		"document", recipientSet210(),
	)

	// --- rejected --------------------------------------------------------
	reject := func(name, stage string, doc []byte, extra ...string) {
		fields := append([]string{"name", name, "outcome", "reject", "stage", stage}, extra...)
		w.record(append(fields, "document", hex.EncodeToString(doc))...)
	}

	xDoc, err := ParseDocument(xWire)
	if err != nil {
		t.Fatal(err)
	}
	macLock, err := encodeMAC(xDoc.MAC)
	if err != nil {
		t.Fatal(err)
	}
	xRecipient := xID.StringWithFormat()
	typeLine := "! " + typeTag + "@"
	closing := "\n---\n"

	flippedMAC := bytes.Clone(xDoc.MAC)
	flippedMAC[0] ^= 0x01
	flippedLock, err := encodeMAC(flippedMAC)
	if err != nil {
		t.Fatal(err)
	}
	reject("reject/flipped-header-mac", "open",
		replaceOnce(t, xWire, macLock, flippedLock), xOpener...)

	flippedPayload := bytes.Clone(xWire)
	flippedPayload[len(flippedPayload)-1] ^= 0x01
	reject("reject/flipped-payload-byte", "open", flippedPayload, xOpener...)

	// Strip the P-256 recipient's whole line. The X25519 wrap still
	// unwraps, but the header MAC covers the recipient set (RFC 0008 §6.1).
	pLineStart := bytes.Index(bothWire, []byte("- "+pID.StringWithFormat()))
	pLineEnd := pLineStart + bytes.IndexByte(bothWire[pLineStart:], '\n') + 1
	reject("reject/stripped-recipient-breaks-header-mac", "open",
		append(bytes.Clone(bothWire[:pLineStart]), bothWire[pLineEnd:]...), xOpener...)

	reject("reject/mixed-sealed-and-unsealed-recipients", "parse",
		replaceOnce(t, xWire, "\n"+typeLine, "\n- "+pID.StringWithFormat()+"\n"+typeLine))
	reject("reject/sealed-without-header-mac", "parse",
		replaceOnce(t, xWire, typeLine+macLock, "! "+typeTag))
	reject("reject/non-utf8-description", "parse",
		[]byte("---\n# \xff\xfe not utf8\n! "+typeTag+"\n---\n"))
	reject("reject/unknown-markl-format", "parse",
		[]byte("---\n- "+purposeRecipient+"@"+mustBlech32(t, "no_such_format", fixedBytes(32, 0xe0))+"\n! "+typeTag+"\n---\n"))
	reject("reject/at-reference-with-inline-body", "parse",
		[]byte("---\n@ "+mustBlech32(t, markl.FormatIdHashBlake2b256, fixedBytes(32, 0xe0))+"\n! "+typeTag+"\n---\n\ninline\n"))

	reject("reject/wrap-lock-without-purpose", "parse", replaceOnce(t, xWire, wrapLock, " < "))
	reject("reject/wrap-lock-under-recipient-purpose", "parse",
		replaceOnce(t, xWire, wrapLock, " < "+purposeRecipient+"@"))
	reject("reject/wrap-lock-under-doc-purpose", "parse",
		replaceOnce(t, xWire, wrapLock, " < "+markl.PurposePigpenDocV1+"@"))
	reject("reject/wrap-lock-under-unknown-purpose", "parse",
		replaceOnce(t, xWire, wrapLock, " < someone-elses-wrap-v9@"))

	// Swap the two recipients' ids, leaving each wrap where it was: an
	// X25519 recipient locked with a P-256 wrap, and the reverse.
	swapped := replaceOnce(t, bothWire, "- "+xRecipient, "- \x00")
	swapped = replaceOnce(t, swapped, "- "+pID.StringWithFormat(), "- "+xRecipient)
	swapped = replaceOnce(t, swapped, "- \x00", "- "+pID.StringWithFormat())
	reject("reject/wrap-format-of-the-other-key-family", "parse", swapped)

	reject("reject/non-encryption-recipient-with-wrap", "parse",
		replaceOnce(t, xWire, "- "+xRecipient, "- "+sshAuthID.StringWithFormat()))

	shortWrap := markl.PurposePigpenWrapV1 + "@" + mustBlech32(t, markl.FormatIdPigpenWrapX25519, fixedBytes(63, 0xe0))
	wrapStart := bytes.Index(xWire, []byte(wrapLock)) + len(" < ")
	wrapEnd := wrapStart + bytes.IndexByte(xWire[wrapStart:], '\n')
	reject("reject/wrap-of-the-wrong-length", "parse",
		append(append(bytes.Clone(xWire[:wrapStart]), shortWrap...), xWire[wrapEnd:]...))

	reject("reject/header-mac-of-the-wrong-length", "parse",
		replaceOnce(t, xWire, macLock, mustBlech32(t, markl.FormatIdPigpenHeaderMac, fixedBytes(31, 0xe0))))
	reject("reject/empty-header-mac-lock", "parse", replaceOnce(t, xWire, macLock, ""))
	reject("reject/header-mac-lock-with-purpose", "parse",
		replaceOnce(t, xWire, typeLine, typeLine+markl.PurposePigpenDocV1+"@"))
	reject("reject/empty-recipient-line", "parse", []byte("---\n- \n! "+typeTag+"\n---\n"))
	reject("reject/empty-recipient-with-wrap", "parse", replaceOnce(t, xWire, xRecipient, ""))
	reject("reject/second-type-line", "parse",
		replaceOnce(t, xWire, closing, "\n! "+typeTag+closing))
	reject("reject/missing-type-line", "parse",
		[]byte("---\n- "+xRecipient+"\n---\n"))
	reject("reject/unknown-type", "parse",
		[]byte("---\n- "+xRecipient+"\n! pigpen-v2\n---\n"))

	path := filepath.FromSlash(pigpenVectorsPath)
	if err := os.WriteFile(path, w.out.Bytes(), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

// recipientSet210 is the #210 interop recipient-set vector, carried over.
func recipientSet210() string { return recipientSet }
