// Code generated by dagnabit (0.6.2+9d069d9); DO NOT EDIT.

package agent

import internal "code.linenisgreat.com/piggy/go/internal/delta/agent"

// AgentECDHOracle performs the card-bound P-256 scalar multiplication
// through an ssh-agent's ecdh@joyent.com extension, which piggy-agent
// serves for the PIV slot-9D key and forwards to its upstreams. The private
// scalar never leaves the card.
//
// It satisfies pigpen's ECDHOracle interface structurally, so a sealed
// pigpen document opens with:
//
//	sock, err := agent.ResolveAuthSock()
//	plaintext, err := doc.Open(agent.AgentECDHOracle{SocketPath: sock}, nil)
//
// The extension call is implemented here, not through dewey's pivy
// client, because the two agents frame the reply differently and this
// client reads both (see parseECDHResponse).
type AgentECDHOracle = internal.AgentECDHOracle

// DiscoveredKey is one agent-resident key surfaced by the Discover*
// helpers: its markl Id (stamped under the appropriate format) plus the
// SSH key type and comment for display.
type DiscoveredKey = internal.DiscoveredKey

// ConnectEcdsaP256AgentSigner connects to $SSH_AUTH_SOCK and returns an
// ssh.Signer backed by the agent's ECDSA P-256 key whose SEC1-compressed
// ECDH point matches compressed. The returned io.Closer owns the agent
// connection.
var ConnectEcdsaP256AgentSigner = internal.ConnectEcdsaP256AgentSigner

// ConnectSSHAgentSigner connects to the agent at $SSH_AUTH_SOCK and
// returns a crypto.Signer backed by the agent key whose Ed25519 public
// key matches publicKey. The returned io.Closer owns the agent
// connection; close it when done signing.
var ConnectSSHAgentSigner = internal.ConnectSSHAgentSigner

// DiscoverAgentECDHKeysVerbose discovers ECDSA P-256 keys from the agent
// whose unix socket path is held in the named environment variable (e.g.
// PIGGY_AUTH_SOCK to target piggy-agent instead of the agent fronted by
// SSH_AUTH_SOCK).
var DiscoverAgentECDHKeysVerbose = internal.DiscoverAgentECDHKeysVerbose

// DiscoverAgentEd25519KeysVerbose discovers Ed25519 keys from the agent
// whose unix socket path is held in the named environment variable (e.g.
// PIGGY_AUTH_SOCK to target piggy-agent instead of the agent fronted by
// SSH_AUTH_SOCK).
var (
	DiscoverAgentEd25519KeysVerbose    = internal.DiscoverAgentEd25519KeysVerbose
	DiscoverPivyAgentECDHKeys          = internal.DiscoverPivyAgentECDHKeys
	DiscoverPivyAgentECDHKeysVerbose   = internal.DiscoverPivyAgentECDHKeysVerbose
	DiscoverSSHAgentECDHKeys           = internal.DiscoverSSHAgentECDHKeys
	DiscoverSSHAgentECDHKeysVerbose    = internal.DiscoverSSHAgentECDHKeysVerbose
	DiscoverSSHAgentEd25519Keys        = internal.DiscoverSSHAgentEd25519Keys
	DiscoverSSHAgentEd25519KeysVerbose = internal.DiscoverSSHAgentEd25519KeysVerbose
)

// ErrAgent marks a failure to get an answer out of the agent: no socket
// variable set, a socket nobody listens on, a key the agent does not hold,
// a card or PIN failure the agent reported, or a reply this client could
// not use. Test for it with IsErrAgent.
//
// It is what tells "the agent could not be asked" apart from "this
// ciphertext is not for this key", which an AEAD failure means. A reader
// that masks the first as the second sends the user looking in the wrong
// place.
var ErrAgent = internal.ErrAgent

// IsErrAgent reports whether err is, or wraps, ErrAgent.
var IsErrAgent = internal.IsErrAgent

// PivyEcdhP256GetIOWrapper builds a pivy IOWrapper that encrypts to, and
// decrypts for, a PIV slot-9D ECDH recipient (the pivy_ecdh_p256_pub
// pubkey carried by id).
//
// The age stanza format is dewey's pivy.IOWrapper, unchanged, so blobs
// already written stay readable. The on-card ECDH is NOT dewey's agent
// client: it is this package's agentECDH. dewey v0.5.0's client reads
// only the reply framing of the C pivy-agent and takes piggy-agent's
// echoed extension name for the shared secret, so nothing decrypted
// through piggy-agent (confirmed by madder's bats lane over fibby at
// madder 0ee2def).
//
// The agent socket is resolved at decrypt time with ResolveAuthSock
// (PIGGY_AUTH_SOCK, then SSH_AUTH_SOCK, then PIVY_AUTH_SOCK). Building
// the wrapper and encrypting need no agent and no socket variable.
//
// A failure to reach the agent or to get a usable reply is an ErrAgent
// (test with IsErrAgent), so a caller can tell it apart from a
// wrong-recipient AEAD failure.
var PivyEcdhP256GetIOWrapper = internal.PivyEcdhP256GetIOWrapper

// RegisterEcdsaP256SSHFormat swaps the real, agent-backed signer over the
// core's erroring ecdsa_p256_ssh stub (idempotent via sync.Once). The
// signer comes from ConnectEcdsaP256AgentSigner. Adapted from madder,
// which wrote the package-private formats map directly; here we go through
// the exported markl.SwapFormat seam (the stub is guaranteed registered
// by the blank import of markl_registrations in this package).
var RegisterEcdsaP256SSHFormat = internal.RegisterEcdsaP256SSHFormat

// RegisterPivyEcdhP256Format swaps the real pivy-agent-backed
// GetIOWrapper over the core's erroring pivy_ecdh_p256 stub (idempotent
// via sync.Once). Unlike the SSH signing formats it needs no connected
// signer — PivyEcdhP256GetIOWrapper resolves the agent socket lazily at
// decrypt time — so it is fired at init() below, giving importers of this
// package the always-on pivy recipient madder's core init provided before
// the dep-light split.
var RegisterPivyEcdhP256Format = internal.RegisterPivyEcdhP256Format

// RegisterSSHEd25519Format swaps the real, agent-backed signer over the
// core's erroring ed25519_ssh stub (idempotent via sync.Once). The signer
// comes from ConnectSSHAgentSigner. Adapted from madder to call the
// exported markl.SwapFormat seam instead of writing the package-private
// formats map (the stub is registered by this package's blank import of
// markl_registrations).
var RegisterSSHEd25519Format = internal.RegisterSSHEd25519Format

// ResolveAuthSock returns the agent socket a decrypt should use:
// PIGGY_AUTH_SOCK, else SSH_AUTH_SOCK, else PIVY_AUTH_SOCK.
var ResolveAuthSock = internal.ResolveAuthSock
